site_name: streamdeck-gui-ng
copyright: Copyright &copy; 2025 streamdeck-gui-ng
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: art/logo.png
  favicon: img/favicon.ico
  palette:
    primary: indigo
  features:
    - navigation.expand

repo_name: streamdeck-gui-ng
repo_url: https://github.com/millaguie/streamdeck-gui-ng
edit_uri: https://github.com/millaguie/streamdeck-gui-ng/docs

markdown_extensions:
  - admonition

nav:
  - Installation:
    - Arch: installation/arch.md
    - Centos: installation/centos.md
    - Fedora: installation/fedora.md
    - Opensuse: installation/opensuse.md
    - Ubuntu: installation/ubuntu.md
    - From Source: installation/source.md
    - Systemd: installation/systemd.md
  - troubleshooting.md 
  - Contributing:
    - contributing/contributing-guide.md
    - Coding standard: contributing/coding-standard.md
    - Code of conduct: contributing/code-of-conduct.md
    - contributing/acknowledgements.md
     

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/millaguie/streamdeck-gui-ng

