blank_issues_enabled: false
contact_links:
  - name: streamdeck-gui-ng Discussions
    url: https://github.com/millaguie/streamdeck-gui-ng/discussions
    about: Please ask and answer questions here.
  - name: streamdeck-gui-ng Documentation
    url: https://millaguie.github.io/streamdeck-gui-ng/
    about: Please read and review our documentation before opening an issue.

